import StyledComponentsRegistry from "@/_lib/registry";
import type { Metadata } from "next";
import Layout from "./_components/Layout";
import { GlobalStyles } from "./_styles/GlobalStyles";
import localFont from "next/font/local";
import RecoilRootProvider from "@/_lib/recoilRootProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const suite = localFont({
  src: [
    {
      path: "./_font/SUITE-Regular.ttf",
      weight: "normal",
      style: "normal",
    },
  ],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={suite.className}>
      <body>
        <RecoilRootProvider>
          <StyledComponentsRegistry>
            <GlobalStyles />
            <Layout>{children}</Layout>
          </StyledComponentsRegistry>
        </RecoilRootProvider>
      </body>
    </html>
  );
}
